// Generated by Wrangler on Fri Jun 07 2024 22:17:29 GMT+0900 (Japan Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	CONTACTMAIL: Fetcher;
}
